<project>
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.aicommerce</groupId>
    <artifactId>ai-commerce-enterprise</artifactId>
    <version>1.0.0</version>
    <packaging>pom</packaging>

<!--    <modules>-->
<!--        <module>services/product-service</module>-->
<!--        <module>services/inventory-service</module>-->
<!--        <module>services/order-service</module>-->
<!--        <module>services/payment-service</module>-->
<!--        <module>services/notification-service</module>-->
<!--        <module>services/agent-service</module>-->
<!--        <module>services/rag-indexer-service</module>-->
<!--    </modules>-->
</project>